# Generated by Django 5.1.4 on 2025-02-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Aminities', 'Aminities'), ('Categories', 'Categories')], max_length=20)),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Constants',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/properties/2'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/properties/3'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/properties/4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='uploads/properties/1'),
        ),
        migrations.CreateModel(
            name='Aminity',
            fields=[
            ],
            options={
                'verbose_name': 'Aminity',
                'verbose_name_plural': 'Aminities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Property.constant',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Property.constant',),
        ),
        migrations.CreateModel(
            name='PropertyAminities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.property')),
                ('aminity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.aminity')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='aminities',
            field=models.ManyToManyField(related_name='aminities', through='Property.PropertyAminities', to='Property.aminity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 'Categories')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Property.category'),
        ),
    ]
