import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";
import { LoginModel } from "@/components/Models/LoginModel";
import { SignUpModel } from "@/components/Models/SignUpModel";
import { Footer } from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: "Airbnb",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {    
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased overflow-x-hidden`}> 
                <AuthProvider>
                    <Navbar/>
                    <div>
                        {children}
                    </div>
                    <LoginModel/>
                    <SignUpModel/>
                    <Footer />
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    );
}
