import { Categories } from "@/components/Categories";
import Image from "next/image";

export default function Home() {
	return (
		<main className="">
		<Categories/>
		<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
		<Categories/>
		<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
		<Categories/>
		<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
		<Categories/>
		<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
		<Categories/>
		<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
		<Categories/>
		<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
			<Categories/>
		</main>
	);
}
