# Generated by Django 5.1.6 on 2025-03-06 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Aminities', 'Aminities'), ('Categories', 'Categories')], max_length=20)),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Constants',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='uploads/properties/1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/properties/2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/properties/3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/properties/4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAminities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aminity',
            fields=[
            ],
            options={
                'verbose_name': 'Aminity',
                'verbose_name_plural': 'Aminities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Property.constant',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Property.constant',),
        ),
    ]
