# Generated by Django 5.1.6 on 2025-03-06 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyaminities',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.property'),
        ),
        migrations.AddField(
            model_name='propertyaminities',
            name='aminity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.aminity'),
        ),
        migrations.AddField(
            model_name='property',
            name='aminities',
            field=models.ManyToManyField(related_name='aminities', through='Property.PropertyAminities', to='Property.aminity'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 'Categories')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Property.category'),
        ),
    ]
