# Generated by Django 5.1.4 on 2025-04-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_alter_reviews_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/properties/5'),
        ),
    ]
